apiVersion: v1
kind: Service
metadata:
  name: backend-podinfo
  namespace: demo-manifest
  labels:
    app: backend-podinfo
spec:
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: backend-podinfo
