apiVersion: v1
kind: Service
metadata:
  name: frontend-podinfo
  namespace: demo1
  labels:
    app: frontend-podinfo
spec:
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: frontend-podinfo
---
apiVersion: v1
kind: Service
metadata:
  name: backend-podinfo-v1
  namespace: demo1
  labels:
    app: backend-podinfo
    version: v1
spec:
  ports:
    - port: 9898
      targetPort: http
      protocol: TCP
      name: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: backend-podinfo
    version: v1
